remote_theme: pmarsceill/just-the-docs
color_scheme: dark
markdown: GFM
logo: "https://recloudstream.github.io/resources/icon.png"
title: "recloudstream"
url: "https://recloudstream.github.io"

gh_edit_link: true
gh_edit_link_text: "View this page on GitHub."
gh_edit_repository: "https://github.com/recloudstream/recloudstream.github.io"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"

search_enabled: true
search.heading_level: 3
search.previews: 4

aux_links:
  "Visit GitHub":
    - "https://github.com/recloudstream/"
  "Join our Discord":
    - "https://discord.gg/5Hus6fM"

plugins:
  - jekyll-sitemap

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap